# -*- coding: utf-8 -*-
"""Hash.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VFD2VDuW_SR09Z9XStTy7rO6VfZi8Xd4
"""

my_dict={'dave':'001','ave':'002','joe':'003'}
print(my_dict)
type(my_dict)

new_dict=dict()
print(new_dict)
type(new_dict)

new_dict=dict(dave='001',ava='002')
print(new_dict)

emp_details={'Employee':{'dave':{'id':'001','salary':'2000','designation':'team lead'},'ava':{'id':'002','salary':'1000','designation':'associate'}}}
print(emp_details)

my_dict['dave']

print(my_dict)

print(my_dict.keys())

print(my_dict.values())

print(my_dict.get('ave'))

for x in my_dict.values():
  print(x)

for x,y in my_dict.items():
  print(x,y)

my_dict['dave']='004'
my_dict['chris']='003'
print(my_dict)

my_dict.pop('ave')

my_dict.popitem()

del my_dict['dave']

print(my_dict)

import pandas as pd
df=pd.DataFrame(emp_details['Employee'])
print(df)