# -*- coding: utf-8 -*-
"""md5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZYtj2eVm9IIz_I5e2PHd-ov-6fAJy-Zm
"""

import hashlib

def main():
   text="helllo world!"
   textutf8=text.encode("utf-8")
   hash=hashlib.md5(textutf8)
   hexa=hash.hexdigest()
   print(hexa)
   return

main()